### ISSUE TITLE
ENTER wrongly accepts keyword that SPACE don't

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#54] opened 2015-12-30 09:29 UTC
Hi,

In an ABL progrram, typing `DO:` causes auto-completion list to appear.
At this time:
* pressing SPACE will work correcty as it won't insert keyword
* pressing ENTER will insert the currently selected keywod in auto-completion list (`ERROR` in my case)

Can you fix this, please?
Regards,

**Comment by jcaillon** [comment] 2015-12-31 13:09
It does so because you set the option **the ENTER/RETURN key triggers the auto-completion** and because the auto-completion list is displayed automatically after a ":"; so it inserts the selected suggestion. This is an expected behavior.

However you are right, i'll change replace the automatic display of the list after a ":" and insert wait the minimum number of char that you can set in the options.

Fixed in the next release

**Closed by jcaillon** 2015-12-31 13:09 UTC
